# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import keyserver_pb2 as keyserver__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in keyserver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyServerStub(object):
    """Key Server Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReleaseKey = channel.unary_unary(
                '/keyserver.KeyServer/ReleaseKey',
                request_serializer=keyserver__pb2.ReleaseKeyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ReloadKeys = channel.unary_unary(
                '/keyserver.KeyServer/ReloadKeys',
                request_serializer=keyserver__pb2.ReloadKeysRequest.SerializeToString,
                response_deserializer=keyserver__pb2.ReloadKeysResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/keyserver.KeyServer/GetStats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=keyserver__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.GetDetailedStats = channel.unary_unary(
                '/keyserver.KeyServer/GetDetailedStats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=keyserver__pb2.DetailedStatsResponse.FromString,
                _registered_method=True)
        self.TrackUsage = channel.unary_unary(
                '/keyserver.KeyServer/TrackUsage',
                request_serializer=keyserver__pb2.TrackUsageRequest.SerializeToString,
                response_deserializer=keyserver__pb2.TrackUsageResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/keyserver.KeyServer/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=keyserver__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SelectKeysForSession = channel.unary_unary(
                '/keyserver.KeyServer/SelectKeysForSession',
                request_serializer=keyserver__pb2.SelectKeysRequest.SerializeToString,
                response_deserializer=keyserver__pb2.SelectKeysResponse.FromString,
                _registered_method=True)


class KeyServerServicer(object):
    """Key Server Service
    """

    def ReleaseKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetailedStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectKeysForSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReleaseKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseKey,
                    request_deserializer=keyserver__pb2.ReleaseKeyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReloadKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadKeys,
                    request_deserializer=keyserver__pb2.ReloadKeysRequest.FromString,
                    response_serializer=keyserver__pb2.ReloadKeysResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=keyserver__pb2.StatsResponse.SerializeToString,
            ),
            'GetDetailedStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetailedStats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=keyserver__pb2.DetailedStatsResponse.SerializeToString,
            ),
            'TrackUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackUsage,
                    request_deserializer=keyserver__pb2.TrackUsageRequest.FromString,
                    response_serializer=keyserver__pb2.TrackUsageResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=keyserver__pb2.HealthResponse.SerializeToString,
            ),
            'SelectKeysForSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectKeysForSession,
                    request_deserializer=keyserver__pb2.SelectKeysRequest.FromString,
                    response_serializer=keyserver__pb2.SelectKeysResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyserver.KeyServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('keyserver.KeyServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyServer(object):
    """Key Server Service
    """

    @staticmethod
    def ReleaseKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyserver.KeyServer/ReleaseKey',
            keyserver__pb2.ReleaseKeyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyserver.KeyServer/ReloadKeys',
            keyserver__pb2.ReloadKeysRequest.SerializeToString,
            keyserver__pb2.ReloadKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyserver.KeyServer/GetStats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            keyserver__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDetailedStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyserver.KeyServer/GetDetailedStats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            keyserver__pb2.DetailedStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyserver.KeyServer/TrackUsage',
            keyserver__pb2.TrackUsageRequest.SerializeToString,
            keyserver__pb2.TrackUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyserver.KeyServer/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            keyserver__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectKeysForSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyserver.KeyServer/SelectKeysForSession',
            keyserver__pb2.SelectKeysRequest.SerializeToString,
            keyserver__pb2.SelectKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
